/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author Rudi Erwanto
 */
public class KALKULATOR extends javax.swing.JFrame {

   String angka = " ";
double jumlah,angka1,angka2;
int pilih;


    /**
     * Creates new form KALKULATOR
     */
    public KALKULATOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BAGI = new javax.swing.JButton();
        KALI = new javax.swing.JButton();
        KURANG = new javax.swing.JButton();
        TAMBAH = new javax.swing.JButton();
        SAMADENGAN = new javax.swing.JButton();
        TITIK = new javax.swing.JButton();
        Nol = new javax.swing.JButton();
        PlusMinus = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        bsp = new javax.swing.JButton();
        Sembilan = new javax.swing.JButton();
        Enam = new javax.swing.JButton();
        Tiga = new javax.swing.JButton();
        Dua = new javax.swing.JButton();
        Satu = new javax.swing.JButton();
        Empat = new javax.swing.JButton();
        Tujuh = new javax.swing.JButton();
        Delapan = new javax.swing.JButton();
        Lima = new javax.swing.JButton();
        DISPLAY = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KALKULATOR");
        setResizable(false);
        getContentPane().setLayout(null);

        BAGI.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BAGI.setText("÷");
        BAGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAGIActionPerformed(evt);
            }
        });
        getContentPane().add(BAGI);
        BAGI.setBounds(280, 120, 90, 80);

        KALI.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        KALI.setText("X");
        KALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KALIActionPerformed(evt);
            }
        });
        getContentPane().add(KALI);
        KALI.setBounds(280, 200, 90, 80);

        KURANG.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        KURANG.setText("-");
        KURANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KURANGActionPerformed(evt);
            }
        });
        getContentPane().add(KURANG);
        KURANG.setBounds(280, 280, 90, 80);

        TAMBAH.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        TAMBAH.setText("+");
        TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAMBAHActionPerformed(evt);
            }
        });
        getContentPane().add(TAMBAH);
        TAMBAH.setBounds(280, 360, 90, 80);

        SAMADENGAN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        SAMADENGAN.setText("=");
        SAMADENGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAMADENGANActionPerformed(evt);
            }
        });
        getContentPane().add(SAMADENGAN);
        SAMADENGAN.setBounds(280, 440, 90, 160);

        TITIK.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        TITIK.setText(".");
        TITIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TITIKActionPerformed(evt);
            }
        });
        getContentPane().add(TITIK);
        TITIK.setBounds(190, 520, 90, 80);

        Nol.setBackground(new java.awt.Color(255, 255, 255));
        Nol.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Nol.setText("0");
        Nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NolActionPerformed(evt);
            }
        });
        getContentPane().add(Nol);
        Nol.setBounds(100, 520, 90, 80);

        PlusMinus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        PlusMinus.setText("±");
        PlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(PlusMinus);
        PlusMinus.setBounds(10, 520, 90, 80);

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton15.setText("CE");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(10, 200, 90, 80);

        Clear.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(100, 200, 90, 80);

        bsp.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bsp.setText("←");
        bsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bspActionPerformed(evt);
            }
        });
        getContentPane().add(bsp);
        bsp.setBounds(190, 200, 90, 80);

        Sembilan.setBackground(new java.awt.Color(255, 255, 255));
        Sembilan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Sembilan.setText("9");
        Sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SembilanActionPerformed(evt);
            }
        });
        getContentPane().add(Sembilan);
        Sembilan.setBounds(190, 280, 90, 80);

        Enam.setBackground(new java.awt.Color(255, 255, 255));
        Enam.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Enam.setText("6");
        Enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnamActionPerformed(evt);
            }
        });
        getContentPane().add(Enam);
        Enam.setBounds(190, 360, 90, 80);

        Tiga.setBackground(new java.awt.Color(255, 255, 255));
        Tiga.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Tiga.setText("3");
        Tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TigaActionPerformed(evt);
            }
        });
        getContentPane().add(Tiga);
        Tiga.setBounds(190, 440, 90, 80);

        Dua.setBackground(new java.awt.Color(255, 255, 255));
        Dua.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Dua.setText("2");
        Dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuaActionPerformed(evt);
            }
        });
        getContentPane().add(Dua);
        Dua.setBounds(100, 440, 90, 80);

        Satu.setBackground(new java.awt.Color(255, 255, 255));
        Satu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Satu.setText("1");
        Satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuActionPerformed(evt);
            }
        });
        getContentPane().add(Satu);
        Satu.setBounds(10, 440, 90, 80);

        Empat.setBackground(new java.awt.Color(255, 255, 255));
        Empat.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Empat.setText("4");
        Empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpatActionPerformed(evt);
            }
        });
        getContentPane().add(Empat);
        Empat.setBounds(10, 360, 90, 80);

        Tujuh.setBackground(new java.awt.Color(255, 255, 255));
        Tujuh.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Tujuh.setText("7");
        Tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuhActionPerformed(evt);
            }
        });
        getContentPane().add(Tujuh);
        Tujuh.setBounds(10, 280, 90, 80);

        Delapan.setBackground(new java.awt.Color(255, 255, 255));
        Delapan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Delapan.setText("8");
        Delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelapanActionPerformed(evt);
            }
        });
        getContentPane().add(Delapan);
        Delapan.setBounds(100, 280, 90, 80);

        Lima.setBackground(new java.awt.Color(255, 255, 255));
        Lima.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Lima.setText("5");
        Lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimaActionPerformed(evt);
            }
        });
        getContentPane().add(Lima);
        Lima.setBounds(100, 360, 90, 80);

        DISPLAY.setEditable(false);
        DISPLAY.setBackground(new java.awt.Color(51, 255, 204));
        DISPLAY.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        DISPLAY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(DISPLAY);
        DISPLAY.setBounds(10, 10, 370, 100);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jButton13.setText("%");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(10, 120, 90, 80);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jButton16.setText("√");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(100, 120, 90, 80);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("x²");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 120, 90, 80);

        setSize(new java.awt.Dimension(401, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NolActionPerformed
        // TODO add your handling code here:
        angka += "0";
DISPLAY.setText(angka);
    }//GEN-LAST:event_NolActionPerformed

    private void SatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuActionPerformed
        // TODO add your handling code here:
        angka += "1";
DISPLAY.setText(angka);
    }//GEN-LAST:event_SatuActionPerformed

    private void DuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuaActionPerformed
        // TODO add your handling code here:
        angka += "2";
DISPLAY.setText(angka);
    }//GEN-LAST:event_DuaActionPerformed

    private void TigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigaActionPerformed
        // TODO add your handling code here:
        angka += "3";
DISPLAY.setText(angka);
    }//GEN-LAST:event_TigaActionPerformed

    private void EmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpatActionPerformed
        // TODO add your handling code here:
        angka += "4";
DISPLAY.setText(angka);
    }//GEN-LAST:event_EmpatActionPerformed

    private void LimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimaActionPerformed
        // TODO add your handling code here:
        angka += "5";
DISPLAY.setText(angka);
    }//GEN-LAST:event_LimaActionPerformed

    private void EnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnamActionPerformed
        // TODO add your handling code here:
        angka += "6";
DISPLAY.setText(angka);
    }//GEN-LAST:event_EnamActionPerformed

    private void TujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuhActionPerformed
        // TODO add your handling code here:
        angka += "7";
DISPLAY.setText(angka);
    }//GEN-LAST:event_TujuhActionPerformed

    private void DelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelapanActionPerformed
        // TODO add your handling code here:
        angka += "8";
DISPLAY.setText(angka);
    }//GEN-LAST:event_DelapanActionPerformed

    private void SembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembilanActionPerformed
        // TODO add your handling code here:
        angka += "9";
DISPLAY.setText(angka);
    }//GEN-LAST:event_SembilanActionPerformed

    private void TITIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TITIKActionPerformed
        // TODO add your handling code here:
        angka += ".";
DISPLAY.setText(angka);
    }//GEN-LAST:event_TITIKActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        DISPLAY.setText("");
angka1=0.0;
angka2=0.0;
jumlah=0.0;
angka="";
    }//GEN-LAST:event_ClearActionPerformed

    private void TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAMBAHActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
DISPLAY.setText("+");
angka="";
pilih=1;
    }//GEN-LAST:event_TAMBAHActionPerformed

    private void KURANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KURANGActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
DISPLAY.setText("-");
angka="";
pilih=2;
    }//GEN-LAST:event_KURANGActionPerformed

    private void KALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KALIActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
DISPLAY.setText("*");
angka="";
pilih=3;
    }//GEN-LAST:event_KALIActionPerformed

    private void BAGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAGIActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
DISPLAY.setText("/");
angka="";
pilih=4;
    }//GEN-LAST:event_BAGIActionPerformed

    private void SAMADENGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAMADENGANActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            DISPLAY.setText(angka);
            break;
        case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            DISPLAY.setText(angka);
            break;
        case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            DISPLAY.setText(angka);
            break;
        case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            DISPLAY.setText(angka);
            break;
        case 5:
            jumlah = angka1/100;
            angka = Double.toString(jumlah);
            DISPLAY.setText(angka);
            break;
        case 6:
            jumlah = Math.pow(angka1, 2);
            angka = Double.toString(jumlah);
            DISPLAY.setText(angka);
            break;
            default:
            break;
    }//GEN-LAST:event_SAMADENGANActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
DISPLAY.setText("%");
angka="";
pilih=5;
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
         double ops = Double.parseDouble(String.valueOf(DISPLAY.getText()));
        ops = Math.sqrt(ops);
        DISPLAY.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButton16ActionPerformed

    private void bspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bspActionPerformed
        // TODO add your handling code here:
        String bsp = null;
        if(DISPLAY.getText().length() > 0)
        {
            StringBuilder strB = new StringBuilder(DISPLAY.getText());
            strB.deleteCharAt(DISPLAY.getText().length() - 1);
            bsp = strB.toString();
            DISPLAY.setText(bsp);
        }
    }//GEN-LAST:event_bspActionPerformed

    private void PlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusMinusActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(DISPLAY.getText()));
        ops = ops * (-1);
        DISPLAY.setText(String.valueOf(ops));
    }//GEN-LAST:event_PlusMinusActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
          DISPLAY.setText("");
angka1=0.0;
angka2=0.0;
jumlah=0.0;
angka="";
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          angka1=Double.parseDouble(angka);
DISPLAY.setText("²");
angka="";
pilih =6;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String [] args) {
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KALKULATOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAGI;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField DISPLAY;
    private javax.swing.JButton Delapan;
    private javax.swing.JButton Dua;
    private javax.swing.JButton Empat;
    private javax.swing.JButton Enam;
    private javax.swing.JButton KALI;
    private javax.swing.JButton KURANG;
    private javax.swing.JButton Lima;
    private javax.swing.JButton Nol;
    private javax.swing.JButton PlusMinus;
    private javax.swing.JButton SAMADENGAN;
    private javax.swing.JButton Satu;
    private javax.swing.JButton Sembilan;
    private javax.swing.JButton TAMBAH;
    private javax.swing.JButton TITIK;
    private javax.swing.JButton Tiga;
    private javax.swing.JButton Tujuh;
    private javax.swing.JButton bsp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    // End of variables declaration//GEN-END:variables
}
